services:
  my_flask:
    container_name: my_flask
    image: my_flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    volumes:
#      - ./crm.db:/crm.db
    restart: always

  my_nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - my_flask
    restart: always

  # my_certbot:
  #   image: certbot/certbot
  #   container_name: my_certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - my_nginx
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email meswff@gmail.com -d tulaastoriabot.ru --agree-tos
